### ISSUE TITLE
메인 - Input 기능

### ISSUE THREAD

**Issue by sanginchun** [woowa-techcamp-2021/cashbook-03#18]
## 개요
Input 바 입력 및 전송 기능

## 브랜치명
fe/input-bar

## 단계별 진행상황
- [x] 일자 선택 (input type=date 으로, *이번 달만 선택 가능) / 커스터마이징은 나중에 선택
- [x] 분류: 지출(default) / 수입 드롭다운
- [x] 카테고리: 분류에 따라서 각각 다른 카테고리 드롭다운
- [ ] 내용: (선택) 창 띄우기
- [x] 결제수단: 분류가 수입일 때는 disabled / 지출일 때는 결제수단 추가 및 삭제 가능
- [x] 금액: 지출 / 수입에 따라 - / + 자동으로 바뀜 (validation)
- [x] 완료버튼: 전부 입력됐을 때 스타일링 변경
- [ ] 드롭다운 열려있는 상태에서 어디든 클릭시 닫히게 -- 다른 컴포넌트라서 불가능?? 일단은 안함

## 예상시간
- 4h

**Comment by yoonminsang** [comment]
소요시간 : 12시간도 더걸린듯...
