### ISSUE TITLE
백엔드 기본 세팅

### ISSUE THREAD

**Issue by sanginchun** [woowa-techcamp-2021/cashbook-03#2]
## 개요
기본적인 백엔드 구조 설정:  routes / controllers / service / repository / loaders

## 브랜치명
be/setting

## 단계별 진행상황
- [x] 기본적인 패키지 설치 및 디렉토리 설정
- [x] sequelize 설치 및 설정

## 예상시간
- 12h

**Comment by sanginchun** [comment]
소요 시간: 12h

**Comment by SecretJuJu** [comment]
#34 
에러처리 관련해서 코멘트 달았습니다 :)
