### ISSUE TITLE
로그인

### ISSUE THREAD

**Issue by sanginchun** [woowa-techcamp-2021/cashbook-03#3]
## 개요
로그인 기능 (인증)

## 브랜치명
be/login

## 단계별 진행상황
- [x] passport 설정
- [x] passport 로컬
- [x] passport github 로그인
- [ ] (선택) 라이브러리 사용하지 않고 OAuth 로그인 구현

## 기타
민상님이 주도적으로 구현하고, 코드 리뷰를 꼼꼼하게 해서 공부해나가는 방식으로 진행

## 예상시간
- 3h

**Comment by yoonminsang** [comment]
구현시간 : 5h

- 삽질을 너무 많이 했다.... 글씨를 잘읽자. 꼼꼼히
