### ISSUE TITLE
AWS 배포

### ISSUE THREAD

**Issue by sanginchun** [woowa-techcamp-2021/cashbook-03#4]
## 개요
FE, BE 기본적인 설정이 끝난 뒤 바로 배포하기

## 브랜치명
미정

## 단계별 진행상황
- [x] 수동으로 배포
- [x] 자동 배포

## 예상시간
- 수동: 1h
- 자동: 3h

**Comment by yoonminsang** [comment]
소요시간 : 수동 0.5h?
